Dodan sonar stuff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -126,6 +126,60 @@ jobs:
           name: frontend-coverage
           path: frontend/coverage
 
+  sonarcloud:
+    name: SonarCloud analysis
+    runs-on: ubuntu-latest
+    needs: [backend, frontend]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Download backend coverage
+        uses: actions/download-artifact@v4
+        with:
+          name: backend-coverage
+          path: backend/coverage
+
+      - name: Download frontend coverage
+        uses: actions/download-artifact@v4
+        with:
+          name: frontend-coverage
+          path: frontend/coverage
+
+      - name: SonarCloud Scan
+        uses: SonarSource/sonarqube-scan-action@v7
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: https://sonarcloud.io
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+
+  quality-gate:
+    name: SonarCloud Quality Gate
+    runs-on: ubuntu-latest
+    needs: sonarcloud
+    if: github.event_name == 'push' && github.ref == 'refs/heads/production'
+    steps:
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install -y jq
+
+      - name: Check quality gate via API
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_PROJECT_KEY: Tevc25_todoapp_rirs
+        run: |
+          status=$(curl -s -u "${SONAR_TOKEN}:" \
+            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY}" \
+            | jq -r '.projectStatus.status')
+
+          echo "Quality Gate status: $status"
+
+          if [ "$status" != "OK" ]; then
+            echo "Quality Gate FAILED → blocking production."
+            exit 1
+          fi
+
 
   # ----------------------------
   # GitHub Pages (statična stran iz ./site)
@@ -195,7 +249,7 @@ jobs:
   docker-prod:
     name: Build & push Docker images (prod)
     runs-on: ubuntu-latest
-    needs: [backend, frontend]
+    needs: [backend, frontend, quality-gate]
     if: github.event_name == 'push' && github.ref == 'refs/heads/production'
     environment: Production
     steps:
